### ISSUE TITLE
Fall-back Simplejson import 

### ISSUE THREAD

**Issue by JoeJasinski** [taichino/prettyprint#1]
Newer versions of python (I think 2.6+) build in the simplejson support (and just call it json).  Might be worth making the import in prettyprint.py fall back to use the built-in version to remove the dependency on the external simplejson program. 

<pre>
try:
   import simplejson as json
except ImportError:
   import json
</pre>

This prettyprint tool is pretty cool.  Thanks for writing and sharing it. 

Joe

**Comment by taichino** [comment]
Thank you very much for your feedback!
and very sorry for my late response...

I've added the code you recommended in version 0.1.4.

**Comment by taichino** [comment]
This issue was resolved in version 0.1.4

**Comment by JoeJasinski** [comment]
Glad to help.
